export const data = {
  contexto: {
    headline: 'R$ 115B em Ativos Judiciais: A Nova Fronteira de Capital no Brasil',
    subheadline: 'Três convergências estruturais — reforma tributária, regulação CVM 175 e consolidação do mercado — criam uma janela de oportunidade de 12 a 18 meses para quem integrar banking, tributação e advocacia em um único ecossistema.',
    marketSize: {
      title: 'Dimensão do Mercado e Implicações Estratégicas',
      items: [
        { label: 'Estoque total de precatórios', value: 'R$ 115B', context: '1,2% do PIB — capital massivo subalocado por fragmentação' },
        { label: 'Passivo federal na LOA 2026', value: 'R$ 69B', context: 'Maior volume orçamentário da história para precatórios federais' },
        { label: 'Credores federais', value: '270K+', context: 'Base atomizada — sem canal integrado de acesso a capital' },
        { label: 'Volume transacionado (2023)', value: 'R$ 491B', context: 'CNJ — liquidez crescente, mas ineficiente sem integração' },
      ],
    },
    growthDynamics: {
      title: 'Aceleração do Segmento',
      items: [
        { segment: 'Fintechs de precatórios', growth: '50% a.a.', observation: 'Acelerado; consolidando' },
        { segment: 'FIDCs de precatórios', growth: '87.8%', observation: 'Explosão regulatória (CVM 175)' },
        { segment: 'Precato (benchmark)', growth: '~R$ 250M/ano', observation: 'R$ 1,5B intermediado em 6 anos' },
        { segment: 'Prêambulo Bank', growth: 'R$ 1,2B/ano', observation: 'Crescimento 30-40%' },
        { segment: 'GCB / PeerBR', growth: 'R$ 3B crédito', observation: '200K+ clientes' },
        { segment: 'Tokenização / RWA', growth: 'R$ 1B+', observation: 'Acura Capital (Hathor)' },
      ],
    },
    competitiveMap: {
      title: 'Posicionamento de Players e Lacunas',
      description: 'Onde os líderes atuais operam e onde reside a oportunidade de integração.',
      players: [
        { name: 'Precato', core: 'Financeiro', strength: 'Alto (liderança R$1,5B)', gap: 'Sem tributária integrada', risk: 'Alto (consolidação)' },
        { name: 'Prêambulo Bank', core: 'Advocacia', strength: 'Alto (1M+ advogados)', gap: 'Sem financeira/tributária', risk: 'Médio-Alto' },
        { name: 'XP Litigation', core: 'Fundos', strength: 'Médio (marca)', gap: 'Sem originação/banco', risk: 'Médio' },
        { name: 'Bancos Tradicionais', core: 'Corporate', strength: 'Médio (reputação)', gap: 'Sem especialização/velocidade', risk: 'Médio' },
        { name: 'GCB / PeerBR', core: 'Holding Fintech', strength: 'Alto (R$3B crédito)', gap: 'Sem jurídico próprio', risk: 'Médio-Alto' },
      ],
      insight: 'Nenhum player domina o triângulo Banking + Tributação + Advocacia. O vazio estratégico é a tese.',
    },
    triggers: {
      title: 'Três Convergências e a Janela de Oportunidade',
      description: 'Vetores estruturais convergindo. A janela para posicionamento estratégico se fecha em 18 meses.',
      items: [
        {
          title: 'Reforma Tributária (2026-2033)',
          implication: 'Demanda puxada por reestruturação fiscal obrigatória.',
          details: ['R$ 50B+ em projetos de conformidade nos próximos 7 anos', 'Empresas precisarão de compensação estruturada em massa'],
        },
        {
          title: 'Regulação CVM 175',
          implication: 'Barreira de entrada removida — capital abundante para FIDCs.',
          details: ['Padronização de direitos creditórios acelera securitização', 'Acesso a funding institucional sem restrições de originação'],
        },
        {
          title: 'Consolidação do Mercado (12-18 meses)',
          implication: 'Primeiros-movers capturam market share definitivo.',
          details: ['Players escalando 50%+ a.a. — concentração acelerada', 'Janela para posicionamento como plataforma integrada se fechando'],
        },
      ],
      window: 'A janela de oportunidade estratégica se fecha em aproximadamente 18 meses. Quem não se posicionar agora como plataforma integrada corre o risco de ser consolidado.',
    },
  },
  posicionamento: {
    headline: 'Onde Está o Vazio: Lacunas na Matriz Competitiva',
    subheadline: 'O mercado de ativos judiciais cresce 50%+ a.a., mas ninguém integra banking, tributação e advocacia no mesmo fluxo. O vazio estratégico é a oportunidade.',
    swot: {
      title: 'Forças e Fragilidades Estruturais do Setor',
      strengths: [
        { text: 'R$ 115B TAM com crescimento 50%+ a.a.', priority: 'critica', leverage: 'Base para captura de valor em escala' },
        { text: 'Regulação favorável (CVM 175 + Reforma Tributária)', priority: 'importante', leverage: 'Vento a favor para estruturação de FIDCs' },
        { text: 'Demanda sistêmica não cíclica', priority: 'importante', leverage: 'Resiliência independente de cenário macro' },
        { text: 'Baixa penetração de plataformas digitais', priority: 'media', leverage: 'Oportunidade de disrupção via tecnologia' },
      ],
      weaknesses: [
        { text: 'Fragmentação da originação — 270K+ credores sem conexão', priority: 'critica', leverage: 'Integração digital como barreira de entrada' },
        { text: 'Ausência de padrão de precificação no mercado secundário', priority: 'importante', leverage: 'Spread de informação = margem para quem padronizar' },
        { text: 'Silos de serviços (jurídico ≠ financeiro ≠ tributário)', priority: 'critica', leverage: 'Integração vertical = vantagem competitiva duradoura' },
        { text: 'Regulação ainda em movimento — risco de mudança de regras', priority: 'media', leverage: 'Exige compliance ágil como competência central' },
      ],
      opportunities: [
        { text: 'Integração Banking + Tributária + Advocacia (modelo inédito)', priority: 'critica', leverage: 'Oceano azul — sem concorrente direto no curto prazo' },
        { text: 'Distribuição B2B2C via ecossistemas de ERP (Conta Azul, Omie)', priority: 'importante', leverage: 'Escala sem custo de aquisição direta' },
        { text: 'Compensação estruturada pós-reforma tributária', priority: 'importante', leverage: 'Demanda obrigatória por reestruturação fiscal' },
        { text: 'FIDC de varejo com cotas acessíveis (R$ 5K+)', priority: 'media', leverage: 'Novo pool de capital de investidores qualificados' },
      ],
      threats: [
        { text: 'Entrada de bancos tradicionais com capital ilimitado', priority: 'critica', leverage: 'Exige velocidade de execução e barreiras de relacionamento' },
        { text: 'Consolidação acelerada — líderes escalando 50%+ a.a.', priority: 'importante', leverage: 'Janela de catch-up se fechando rapidamente' },
        { text: 'Mudanças regulatórias imprevisíveis', priority: 'media', leverage: 'Diversificação de linhas como hedge natural' },
        { text: 'Novos entrantes com capital de venture', priority: 'media', leverage: 'Vantagem de conhecimento setorial vs. velocidade digital' },
      ],
    },
    gaps: {
      title: 'Espaços Vazios na Matriz Competitiva',
      items: [
        { title: 'Integração Vertical', description: 'Ninguém executa Banking + Tributação + Advocacia no mesmo fluxo. O cliente precisa de 3 a 4 fornecedores diferentes para resolver um problema integrado.' },
        { title: 'Distribuição B2B2C', description: 'Nenhum player desenvolveu presença em ecossistemas de ERP (Conta Azul, Omie, SAP). A distribuição ainda é reativa e baseada em relacionamento.' },
        { title: 'Transparência de Precificação', description: 'Mercado opera via propostas comerciais subjetivas. Ausência de tabela pública gera desconfiança e ineficiência de alocação.' },
        { title: 'FIDC de Varejo', description: 'Ausência de cotas acessíveis (R$ 5K+) para investidores qualificados. Mercado de capitais ainda restrito a grandes players institucionais.' },
      ],
    },
  },
  diagnostico: {
    headline: 'O Paradoxo BHG: 30 Anos de Expertise, Zero Presença Digital',
    subheadline: 'BHG tem capacidade técnica para competir em qualquer dimensão do mercado de ativos judiciais — mas sua expressão de mercado é praticamente invisível. Três gaps críticos explicam o paradoxo.',
    matrix: {
      title: 'Posição de BHG na Matriz de Integração',
      description: 'O gap entre a capacidade instalada e a expressão de mercado.',
      dimensions: [
        { label: 'Especialização Jurídica', value: 'Muito Alta (CEO 30y)', status: 'exists' },
        { label: 'Integração Banking', value: 'Em expansão — base existente', status: 'exists' },
        { label: 'Integração Tributária', value: '10 anos de operação consolidada', status: 'exists' },
        { label: 'Plataforma Digital', value: 'Inexistente — operação em silos', status: 'critical', gap: 'GAP CRÍTICO #1' },
        { label: 'Marca e Posicionamento', value: 'Genérica — invisível no mercado', status: 'critical', gap: 'GAP CRÍTICO #2' },
        { label: 'Distribuição e Canais', value: 'Nenhum — 100% reativa', status: 'critical', gap: 'GAP CRÍTICO #3' },
      ],
    },
    swot: {
      title: 'Análise de Capacidade Interna BHG',
      strengths: [
        { text: 'CEO com 30 anos de contencioso de massa', priority: 'critica', leverage: 'Profundidade técnica como alicerce da tese' },
        { text: 'BHG Consultoria — 10 anos de operação tributária', priority: 'importante', leverage: 'Base para integração tributo-financeira' },
        { text: 'Escritório próprio desde 2012', priority: 'media', leverage: 'Estrutura consolidada para suportar crescimento' },
        { text: 'Acesso a ativos e relacionamentos no setor', priority: 'importante', leverage: 'Vantagem de originação vs. entrantes digitais' },
      ],
      weaknesses: [
        { text: 'Sites e marcas fragmentadas — zero unidade de comunicação', priority: 'critica', leverage: 'Unificação digital como alavanca de curto prazo' },
        { text: 'Falta de narrativa de marca e posicionamento de mercado', priority: 'critica', leverage: 'Reposicionamento como plataforma integrada' },
        { text: 'Operação manual — sem processos digitalizados', priority: 'importante', leverage: 'Automação como multiplicador de capacidade' },
        { text: 'Equipe jurídica reduzida para escala', priority: 'media', leverage: 'Tecnologia como alavanca de produtividade' },
      ],
      opportunities: [
        { text: 'Integração tributo-financeira como diferencial competitivo', priority: 'critica', leverage: 'Posicionamento único vs. Precato e Prêambulo' },
        { text: 'Reforma tributária como demanda puxada por serviços integrados', priority: 'importante', leverage: 'Vento a favor para estruturação de compensações' },
        { text: 'Distribuição B2B2C via ERPs e canais parceiros', priority: 'importante', leverage: 'Escala sem investimento em aquisição direta' },
        { text: 'Consolidação de mercado abre espaço para plataformas integradas', priority: 'media', leverage: 'Janela para capturar market share de players fragmentados' },
      ],
      threats: [
        { text: 'Expansão de competidores estabelecidos (Precato, Prêambulo)', priority: 'critica', leverage: 'Velocidade de execução como único diferencial temporal' },
        { text: 'Mudanças regulatórias que alterem o modelo de negócio', priority: 'importante', leverage: 'Flexibilidade de modelo como hedge regulatório' },
        { text: 'Consolidação acelerada pode fechar janela de oportunidade', priority: 'importante', leverage: 'Decisão de posicionamento nos próximos 12 meses' },
      ],
    },
  },
  tese: {
    headline: 'Por Que Integração Gera 3-5x Mais Valor',
    subheadline: 'Empresas integradas (banking + tributação + advocacia) multiplicam valuation por 3-5x versus prestadores de serviços isolados. A tese BHG é capturar esse prêmio via orquestração de jornada.',
    synergy: {
      title: 'Interseção de Serviços: Onde o Capital é Otimizado',
      description: 'Banking + Tributária + Patrimônio não são linhas de negócio separadas — são engrenagens de uma mesma máquina de criação de valor.',
      elements: [
        { label: 'Banking', color: 'blue' },
        { label: 'Tributária', color: 'purple' },
        { label: 'Patrimônio', color: 'emerald' },
      ],
      intersection: {
        label: 'Interseção Estratégica',
        description: 'O cliente que transita por todos os três serviços tem LTV 5x maior, CAC 60% menor e taxa de retenção superior a 90%.',
      },
      example: {
        title: 'Exemplo de Orquestração',
        steps: [
          'Ativo: Precatório R$ 1M + Débito Tributário R$ 1M',
          'Crédito (70% LTV) + Compensação Estruturada → +R$ 200K de ganho líquido',
          'Excedente financeiro → Gestão Patrimonial → Taxa de performance recorrente',
          'Resultado: 3 fluxos de receita de um mesmo cliente, sem custo adicional de aquisição',
        ],
      },
    },
    repositioning: {
      title: 'Mudança de Modelo: De Prestador a Plataforma',
      description: 'Múltiplos de valuation refletem o modelo de negócio: prestadores transacionais são avaliados em 2-3x EBITDA; plataformas integradas alcançam 8-12x EBITDA.',
      from: 'Prestador de Serviços (Transacional — 2-3x EBITDA)',
      to: 'Plataforma de Inteligência (Lock-in — 8-12x EBITDA)',
      valueProp: 'A transição de vender serviços fragmentados para orquestrar a jornada completa do cliente multiplica o valor da empresa.',
    },
    valueChain: {
      title: 'Jornada do Cliente: Loop de Criação de Valor',
      description: 'Do diagnóstico ao patrimônio — cada etapa adiciona uma camada de receita e aprofunda o lock-in do cliente.',
      stages: [
        { label: 'Mapeamento', input: 'Diagnóstico de Ativos', revenue1: 'Zero', revenue2: 'Taxa Diagnóstico', revenue3: 'Zero' },
        { label: 'Liquidez', input: 'Antecipação/Crédito', revenue1: 'Deságio/Fee', revenue2: 'Fluxo de Caixa', revenue3: 'Zero' },
        { label: 'Otimização', input: 'Eficiência Fiscal', revenue1: 'Fee Compensação', revenue2: 'Redução de Passivo', revenue3: 'Zero' },
        { label: 'Patrimônio', input: 'Gestão de Excedente', revenue1: 'Taxa de Gestão', revenue2: 'Performance', revenue3: 'LTV Perpétuo' },
      ],
    },
  },
  modelos: {
    headline: 'Três Caminhos, Três Futuros: Escolha Seu Modelo',
    subheadline: 'Cada arquétipo estratégico representa uma aposta diferente em margem, escala e valuation. A escolha errada pode custar 10x o valor potencial da empresa.',
    models: [
      {
        id: 'especialista',
        name: 'Modelo Especialista',
        subtitle: 'High-Margin, Low-Volume',
        focus: 'UHNW + M&A Complexo',
        ticket: 'R$ 5M - R$ 50M',
        volume: '5-20 clientes/ano',
        revenue: 'Fees altos (2-5%)',
        margin: '55-65%',
        cac: 'Praticamente Zero',
        valuation: 'R$ 80-120M (5y)',
        risk: 'Concentração de Clientes',
        whenToChoose: [
          { type: 'pros', text: 'Sua prioridade é margem, não escala?' },
          { type: 'pros', text: 'Seu diferencial é profundidade técnica, não alcance?' },
          { type: 'cons', text: 'Você aceita ser avaliado em 2-3x EBITDA?' },
        ],
        description: 'Foco em operações de alta complexidade e profundidade de relacionamento. Lucro elevado, escala limitada.',
      },
      {
        id: 'plataforma',
        name: 'Modelo Plataforma',
        subtitle: 'Scale-up via B2B2C',
        focus: 'PMEs via Parceiros',
        ticket: 'R$ 100k - R$ 2M',
        volume: '100-500 clientes/ano',
        revenue: 'Revenue Share (5-10%)',
        margin: '35-45%',
        cac: 'Médio (Parceiros)',
        valuation: 'R$ 300-400M (5y)',
        risk: 'Dependência de Canais',
        whenToChoose: [
          { type: 'pros', text: 'Você quer crescer 10x em 5 anos?' },
          { type: 'pros', text: 'Seu ativo é tecnologia e processos, não relacionamento?' },
          { type: 'cons', text: 'Você aceita depender de canais parceiros para distribuição?' },
        ],
        description: 'Atua como infraestrutura de distribuição para parceiros de ecossistema. Equilíbrio entre escala e margem.',
      },
      {
        id: 'ecossistema',
        name: 'Modelo Ecossistema',
        subtitle: 'Max Retention & Valuation',
        focus: 'Mid-Market + Complexidade',
        ticket: 'R$ 500k - R$ 10M',
        volume: '100-300 clientes/ano',
        revenue: 'Múltiplos Fluxos',
        margin: '40-50%',
        cac: 'Médio-Alto',
        valuation: 'R$ 800M-1.2B (5y)',
        risk: 'Complexidade de Execução',
        whenToChoose: [
          { type: 'pros', text: 'Você quer construir o sistema operacional do mercado?' },
          { type: 'pros', text: 'Seu objetivo é valuation máximo (8-12x EBITDA)?' },
          { type: 'cons', text: 'Você está preparado para a complexidade operacional de integrar tudo?' },
        ],
        description: 'O sistema operacional que retém o cliente em todas as dimensões financeiras. Valuation máximo, execução complexa.',
      },
    ],
    conclusion: 'Não existe modelo certo ou errado — existe o modelo certo para sua visão, seu capital e sua tolerância ao risco. O erro fatal é não escolher.',
  },
};
